{% set name = "llama-index-instrumentation" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_index_instrumentation-{{ version }}.tar.gz
  sha256: 8f0b8535670d917cc7fde9600d5be9e75c0ed8872ddb9b89005d09130ffcff0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - deprecated >=1.2.18
    - pydantic >=2.11.5

test:
  imports:
    - llama_index_instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/run-llama/llama_index
  summary: LlamaIndex is the leading framework for building LLM-powered agents over your data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
