schema_version: 1

context:
  name: llama-index-instrumentation
  version: 0.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/llama_index_instrumentation-${{ version }}.tar.gz
  sha256: 77741c1d9861ead080e6f98350625971488d1e046bede91cec9e0ce2f63ea34a

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - deprecated >=1.2.18
    - pydantic >=2.11.5

tests:
  - python:
      imports:
        - llama_index_instrumentation
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: LlamaIndex is the leading framework for building LLM-powered agents over your data.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/run-llama/llama_index

extra:
  recipe-maintainers:
    - jan-janssen
